### PR TITLE
"made functioning dashboard to be used with RDataFrame and added missing variables in loadRDF() in test_fastSimulation.py"

### PR DESCRIPTION
**Pull request by Trenchcoat95**

### CODE REVIEW

**Comment by miranov25** [comment]
### C++ unit test looks more less OK:

```
Info in <TCanvas::MakeDefCanvas>:  created default TCanvas with name c1
Error in <testFastTracker part reco In pull test P0>: pullAnalytical- FAILED- 0.97      0.97
Info in <testFastTracker part reco In pull test P1 >: pullAnalytical - OK - 1.01        1.03
Error in <testFastTracker part reco In pull test P2>: pullAnalytical- FAILED- 1.06      1.09
Info in <testFastTracker part reco In pull test P3 >: pullAnalytical - OK - 1.01        1.05
Error in <testFastTracker part reco In pull test P4>: pullAnalytical- FAILED- 0.86      0.92
Info in <testFastTracker partFull reco In pull test P0 >: pullAnalytical - OK - 0.99    1.02
Info in <testFastTracker partFull reco In pull test P1 >: pullAnalytical - OK - 1.01    1.03
Error in <testFastTracker partFull reco In pull test P2>: pullAnalytical- FAILED- 1.08  1.15
Info in <testFastTracker partFull reco In pull test P3 >: pullAnalytical - OK - 1.00    1.04
Error in <testFastTracker partFull reco In pull test P4>: pullAnalytical- FAILED- 0.89  1.00
Info in <testFastTracker partFull reco Out pull test P0 >: pullAnalytical - OK - 0.99   1.00
Info in <testFastTracker partFull reco Out pull test P1 >: pullAnalytical - OK - 1.00   1.01
Info in <testFastTracker partFull reco Out pull test P2 >: pullAnalytical - OK - 0.99   1.01
Error in <testFastTracker partFull reco Out pull test P3>: pullAnalytical- FAILED- 1.03 1.06
Error in <testFastTracker partFull reco Out pull test P4>: pullAnalytical- FAILED- 1.06 1.14
Info in <testFastTracker partFull reco Refit pull test P0 >: pullAnalytical - OK - 1.01 1.04
Error in <testFastTracker partFull reco Refit pull test P1>: pullAnalytical- FAILED- 1.05       1.09
Info in <testFastTracker partFull reco Refit pull test P2 >: pullAnalytical - OK - 0.97 1.05
Error in <testFastTracker partFull reco Refit pull test P3>: pullAnalytical- FAILED- 1.07       1.12
Info in <testFastTracker partFull reco Refit pull test P4 >: pullAnalytical - OK - 1.00 1.12

```

**Comment by miranov25** [comment]
The pull definition was wrong - not divided by rms but bar rms2

**Comment by Trenchcoat95** [comment]
Pull tests obtained on the SnapShot (made with 1000 events):
```
testFastTracker snapShot reco In pull test P0 - pullAnalytical - OK - 0.99      1.01 
testFastTracker snapShot reco In pull test P1 - pullAnalytical - OK - 0.99      1.00 
testFastTracker snapShot reco In pull test P2 - pullAnalytical - FAILED - 0.95  0.98 
testFastTracker snapShot reco In pull test P3 - pullAnalytical - FAILED - 0.97  0.98 
testFastTracker snapShot reco In pull test P4 - pullAnalytical - FAILED - 1.02  1.05 

testFastTracker snapShot reco Out pull test P0 - pullAnalytical - OK - 1.01     1.03 
testFastTracker snapShot reco Out pull test P1 - pullAnalytical - OK - 0.99     1.00 
testFastTracker snapShot reco Out pull test P2 - pullAnalytical - OK - 1.01     1.10 
testFastTracker snapShot reco Out pull test P3 - pullAnalytical - FAILED - 1.02 1.04 
testFastTracker snapShot reco Out pull test P4 - pullAnalytical - FAILED - 1.05 1.24 

testFastTracker snapShot reco Refit pull test P0 - pullAnalytical - FAILED - 1.05       1.08 
testFastTracker snapShot reco Refit pull test P1 - pullAnalytical - FAILED - 1.05       1.07 
testFastTracker snapShot reco Refit pull test P2 - pullAnalytical - OK - 1.01   1.11 
testFastTracker snapShot reco Refit pull test P3 - pullAnalytical - FAILED - 1.05       1.09 
testFastTracker snapShot reco Refit pull test P4 - pullAnalytical - FAILED - 1.05       1.27 
```

**Comment by Trenchcoat95** [comment]
Usual pull test on  40000 events sample:
```
Error in <testFastTracker part reco In pull test P0>: pullAnalytical- FAILED- 0.97      0.97
Info in <testFastTracker part reco In pull test P1 >: pullAnalytical - OK - 1.01        1.03
Error in <testFastTracker part reco In pull test P2>: pullAnalytical- FAILED- 1.06      1.09
Info in <testFastTracker part reco In pull test P3 >: pullAnalytical - OK - 1.01        1.05
Error in <testFastTracker part reco In pull test P4>: pullAnalytical- FAILED- 0.86      0.92
Info in <testFastTracker partFull reco In pull test P0 >: pullAnalytical - OK - 0.99    1.02
Info in <testFastTracker partFull reco In pull test P1 >: pullAnalytical - OK - 1.01    1.03
Error in <testFastTracker partFull reco In pull test P2>: pullAnalytical- FAILED- 1.08  1.15
Info in <testFastTracker partFull reco In pull test P3 >: pullAnalytical - OK - 1.00    1.04
Error in <testFastTracker partFull reco In pull test P4>: pullAnalytical- FAILED- 0.89  1.00
Info in <testFastTracker partFull reco Out pull test P0 >: pullAnalytical - OK - 0.99   1.00
Info in <testFastTracker partFull reco Out pull test P1 >: pullAnalytical - OK - 1.00   1.01
Info in <testFastTracker partFull reco Out pull test P2 >: pullAnalytical - OK - 0.99   1.01
Error in <testFastTracker partFull reco Out pull test P3>: pullAnalytical- FAILED- 1.03 1.06
Error in <testFastTracker partFull reco Out pull test P4>: pullAnalytical- FAILED- 1.06 1.14
Info in <testFastTracker partFull reco Refit pull test P0 >: pullAnalytical - OK - 1.01 1.04
Error in <testFastTracker partFull reco Refit pull test P1>: pullAnalytical- FAILED- 1.05       1.09
Info in <testFastTracker partFull reco Refit pull test P2 >: pullAnalytical - OK - 0.97 1.05
Error in <testFastTracker partFull reco Refit pull test P3>: pullAnalytical- FAILED- 1.07       1.12
Info in <testFastTracker partFull reco Refit pull test P4 >: pullAnalytical - OK - 1.00 1.12
```

**Pull request merged**
