### PR TITLE
When Propagate fails -> PropagateToMirrorX

### PR DESCRIPTION
**Pull request by Trenchcoat95**
Modified so that if the propagation fails, then we PropagateToMirrorX() , we find the point with the closest x coordinate and continue from there. Problem with the rotation failures still exists but will require an alternative solution, since it happens AFTER the mirror.

### CODE REVIEW

**Comment by Trenchcoat95** [comment]
Before modifications:
Pulls:
`Info in <testFastTracker partFull reco pull test P0 >: pullAnalytical - OK - 0.97       1.02`
`Info in <testFastTracker partFull reco pull test P1 >: pullAnalytical - OK - 0.99       1.03`
`Info in <testFastTracker partFull reco pull test P2 >: pullAnalytical - OK - 1.04       1.13`
`Info in <testFastTracker partFull reco pull test P3 >: pullAnalytical - OK - 0.99       1.04`
`Error in <testFastTracker partFull reco pull test P4>: pullAnalytical- FAILED- 0.87     1.00`
Logs:
`fastParticle::reconstructParticleFull: 2809`
`fastParticle::reconstructParticleFull: short track 2250`
`fastParticle::reconstructParticleFull: Too few consecutive points 57`
`fastParticle::reconstructParticleFull: Rotation failed 163`
`fastParticle::reconstructParticleFull: Propagation failed 298`
`fastParticle::reconstructParticleFull: Update failed 0`
`fastParticle::reconstructParticleFull: Too big chi2 19`
`fastParticle::reconstructParticleFull: Correct for material failed 12`
`fastParticle::reconstructParticleFull: PropagateToMirrorX failed 10`

**Comment by Trenchcoat95** [comment]
After Modifications:
Pulls:
```
Info in <testFastTracker partFull reco pull test P0 >: pullAnalytical - OK - 0.96       1.01
Info in <testFastTracker partFull reco pull test P1 >: pullAnalytical - OK - 1.01       1.05
Error in <testFastTracker partFull reco pull test P2>: pullAnalytical- FAILED- 1.07     1.15
Info in <testFastTracker partFull reco pull test P3 >: pullAnalytical - OK - 1.01       1.07
Error in <testFastTracker partFull reco pull test P4>: pullAnalytical- FAILED- 0.88     0.98
```
Logs:
```
fastParticle::reconstructParticleFull: 2608
fastParticle::reconstructParticleFull: short track 2314
fastParticle::reconstructParticleFull: Too few consecutive points 60
fastParticle::reconstructParticleFull: Rotation failed 184
fastParticle::reconstructParticleFull: Propagation failed 0
fastParticle::reconstructParticleFull: Update failed 0
fastParticle::reconstructParticleFull: Too big chi2 17
fastParticle::reconstructParticleFull: Correct for material failed 14
fastParticle::reconstructParticleFull: PropagateToMirrorX failed 19
```

**Comment by Trenchcoat95** [comment]
Rotation failure ALWAYS happens right after PropagateToMirrorX(), as shown in plot below:
`treeFast->Draw("(fLoop[]-fLoop[Iteration$+1])","Iteration$>2&&partFull.fStatusMaskIn==0","",40000)`
image

**Comment by miranov25** [comment]
When you change the status to -1 will the bitmask not work anymore? Did I miss something? 
The default was one and each success added some bitmask.
I assume this will not work as you expect

**Comment by miranov25** [comment]
In case the problem happens after propatatetomirrow, maybe we have the same problem as with the propagate, update ...
In case you do not understand, we can meet tomorrow to fix the problem.

**Comment by Trenchcoat95** [comment]
Logs after latest commit:
```
fastParticle::reconstructParticleFull: 2426
fastParticle::reconstructParticleFull: short track 2259
fastParticle::reconstructParticleFull: Too few consecutive points 57
fastParticle::reconstructParticleFull: Rotation failed 30
fastParticle::reconstructParticleFull: Propagation failed 0
fastParticle::reconstructParticleFull: Update failed 0
fastParticle::reconstructParticleFull: Too big chi2 53
fastParticle::reconstructParticleFull: Correct for material failed 13
fastParticle::reconstructParticleFull: PropagateToMirrorX failed 14
```
Pulls after latest commit:
```
Info in <testFastTracker partFull reco pull test P0 >: pullAnalytical - OK - 0.96       1.00
Info in <testFastTracker partFull reco pull test P1 >: pullAnalytical - OK - 1.01       1.05
Info in <testFastTracker partFull reco pull test P2 >: pullAnalytical - OK - 1.06       1.13
Info in <testFastTracker partFull reco pull test P3 >: pullAnalytical - OK - 1.00       1.06
Error in <testFastTracker partFull reco pull test P4>: pullAnalytical- FAILED- 0.87     0.99
```

**Comment by miranov25** [comment]
As I wrote above we should use bitmask to indicate the status.
Default value of bitmask is 0 - nothing happened
2 additional bit to be added: kTrackSkip, and kTrackOK

- We would never use numbers to change the status. 
- we should never use assign only += or |=

```
  enum TrackingBits {
  kTrackRotate   = 0x1,
  kTrackPropagate  = 0x2,
  kTrackCorrectForMaterial =0x4,
  kTrackUpdate =0x8,
  kTrackChi2   =0x10,
  kTrackSkip =0x20,
kTrackOK=0x40
} ;
```

kTrackOK should be set if everything fine Update and Chi2test
kTrackSkip flag should be set if latyer was skipped because of some problems

**Comment by Trenchcoat95** [comment]
After bit mask modification and added protection on Propagate failures:

Pull Test:
```
Info in <testFastTracker partFull reco pull test P0 >: pullAnalytical - OK - 0.97       1.02
Info in <testFastTracker partFull reco pull test P1 >: pullAnalytical - OK - 1.00       1.03
Error in <testFastTracker partFull reco pull test P2>: pullAnalytical- FAILED- 1.09     1.14
Info in <testFastTracker partFull reco pull test P3 >: pullAnalytical - OK - 1.00       1.05
Error in <testFastTracker partFull reco pull test P4>: pullAnalytical- FAILED- 0.88     1.00
```

Logs:
```
fastParticle::reconstructParticleFull: 2480
fastParticle::reconstructParticleFull: short track 2318
fastParticle::reconstructParticleFull: Too few consecutive points 57
fastParticle::reconstructParticleFull: Rotation failed 30
fastParticle::reconstructParticleFull: Propagation failed 30
fastParticle::reconstructParticleFull: Update failed 0
fastParticle::reconstructParticleFull: Too big chi2 29
fastParticle::reconstructParticleFull: Correct for material failed 16
fastParticle::reconstructParticleFull: PropagateToMirrorX failed 0
```

**Comment by Trenchcoat95** [comment]
New possible statuses

- 0: Not entered the cycle
- 1: Just entered the cycle
- 3: Rotation applied
- 7: Propagation applied
- 15: chi2 check passed
- 31: Update applied
- 63: Material correction applied
- 64: PropagateToMirrorX applied with some points skipped
- 65: PropagateToMirrorX applied with no points skipped
- 67: PropagateToMirrorX applied after Propagate failure with no points skipped
- 128: Point Skipped in PropagatetoMirrorX after Propagate failed
- 129: Point Skipped in PropagatetoMirrorX but Propagate didn't fail
- 131: First Point Skipped in PropagatetoMirrorX after Propagate failed
- 143: Skipped Update

**Comment by Trenchcoat95** [comment]
New covariance plot:

image

**Comment by miranov25** [comment]
I think the failure rate is already acceptable
In real use case, we will connect the track segment (legs of helices) and for the brag peak the fit will be done in another direction
higher momenta-> lower momenta-> brag peak
Currently, we are doing it vice versa starting from the end of the trajectory getting optimal parameter at vertex
I future we will do Kalman smoothing (up-down) and brag peak fit will be a separate function

**Comment by miranov25** [comment]
Todo:
get rid of the hardwired constant for the status mask in the test

**Comment by miranov25** [comment]
Relates to #9

**Pull request merged**
